name: YOLO
server:
  cut-layer: b
  clients:
    - 9
    - 3
  model: yolo26n
  batch-size: 1

rabbit:
  address: 192.168.101.234
  username: admin
  password: "123456"
  virtual-host: /

pdd:
  enabled: True
  inter_cloud_bandwidth_MBps: 125.0         # BW giữa các cloud node (1 Gbps LAN)
profile:
  devices_path: src/devices.json
  layer_profile_path: src/layer_profile.json
debug-mode: False
data: video.mp4
log-path: .
compress:
  enable: False
  num_bit: 8
